### ISSUE TITLE
Redmine3.3.0で *自分の活動* を追加するとInternalErrorが発生します

### ISSUE THREAD

**Issue by torut** [vividtone/redmine_vividtone_my_page_blocks#5]
## redmine/log/production.log の抜粋
```
Started GET "/my/page" for <public.ip.address> at 2016-07-01 15:12:05 +0900
Processing by MyController#page as HTML
  Current user: username (id=3)
  Rendered issues/_list_simple.html.erb (17.4ms)
  Rendered issues/_list_simple.html.erb (14.2ms)
  Rendered plugins/redmine_vividtone_my_page_blocks/app/views/my/blocks/_priority_issues.html.erb (194.6ms)
  Rendered issues/_list_simple.html.erb (120.6ms)
  Rendered plugins/redmine_vividtone_my_page_blocks/app/views/my/blocks/_doing_issues.html.erb (143.9ms)
  Rendered issues/_list_simple.html.erb (20.1ms)
  Rendered my/blocks/_issuesassignedtome.html.erb (58.2ms)
  Rendered issues/_list_simple.html.erb (384.5ms)
  Rendered plugins/redmine_vividtone_my_page_blocks/app/views/my/blocks/_neglected_issues.html.erb (399.0ms)
  Rendered plugins/redmine_vividtone_my_page_blocks/app/views/my/blocks/_my_activity.html.erb (76.9ms)
  Rendered my/page.html.erb within layouts/base (876.5ms)
Completed 500 Internal Server Error in 930ms (ActiveRecord: 71.2ms)

ActionView::Template::Error (undefined method `[]' for nil:NilClass):
    1: <%
    2:   current_user = User.current
    3:   events = Redmine::Activity::Fetcher.new(current_user, :author => current_user).events(nil, nil, :limit => 10)
    4:   events_by_day = events.group_by(&:event_date)
    5: %>
    6:
  lib/plugins/acts_as_activity_provider/lib/acts_as_activity_provider.rb:53:in `find_events'
  lib/redmine/activity/fetcher.rb:91:in `block (2 levels) in events'
  lib/redmine/activity/fetcher.rb:90:in `each'
  lib/redmine/activity/fetcher.rb:90:in `block in events'
  lib/redmine/activity/fetcher.rb:89:in `each'
  lib/redmine/activity/fetcher.rb:89:in `events'
  plugins/redmine_vividtone_my_page_blocks/app/views/my/blocks/_my_activity.html.erb:3:in `_plugins_redmine_vividtone_my_page_blocks_app_views_my_blocks__my_activity_html_erb___3883017127610658558_70093547804300'
  app/views/my/page.html.erb:29:in `block in _app_views_my_page_html_erb___1767417655710393970_70093551562580'
  app/views/my/page.html.erb:26:in `each'
  app/views/my/page.html.erb:26:in `_app_views_my_page_html_erb___1767417655710393970_70093551562580'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

## Redmine 環境他

```
Environment:
  Redmine version                3.3.0.stable
  Ruby version                   2.1.5-p273 (2014-11-13) [x86_64-linux]
  Rails version                  4.2.6
  Environment                    production
  Database adapter               Mysql2

Redmine plugins:
  redmine_vividtone_my_page_blocks 20150614
```

**Comment by torut** [comment]
原因は my_page_blocks ではなく、他のプラグイン(Redmine Wiki Extensions Plugin)でした。

お騒がせいたしました。
